config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new', as: 'new'
  get 'tasks/:id', to: 'tasks#show', as: 'task'
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit'
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy', as: 'destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params_create)
    @task.save

    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params_update)

    redirect_to task_path(@task)
  end

  def task_params_create
    params.require(:task).permit(:title, :details)
  end

  def task_params_update
    params.require(:task).permit(:title, :details, :completed)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <% if params[:action] == "edit" %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <% end %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>
  <% @tasks.each do |task| %>
    <p>
      <% if task.completed %>
      <i class="fa fa-check-square"></i>
      <% else %>
      <i class="fa fa-square"></i>
      <% end %>
      <%= link_to task.title, task_path(task) %>-
      <%= link_to destroy_path(task), method: :delete, data: { confirm: "Do you really want to delete this task?" } do %>
      <i class="fa fa-trash-o"></i>
      <% end %>
    </p>
  <% end %>

<%= link_to "Add new Task", new_path %>

app/views/tasks/new.html.erb
<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1><%=@task.title %></h1>
<h3><%= @task.details %></h3>
<% if @task.completed %>
  <p>Completed<i class="fa fa-check-square"></i></p>
<% else %>
  <p>Completed<i class="fa fa-square"></i></p>
<% end %>

<%= link_to "Update task", edit_path %>

<%= link_to "Back to list", tasks_path %>